[[EoM]]
deps = ["LinearAlgebra","Dates","DelimitedFiles"]
path = "/home/minaker/Dropbox/vdc_repo/software/github/EoM.jl/"
uuid = "25d7ee20-f19a-11e8-093a-7b526cbd2d90"
version = "0.1.0"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[DelimitedFiles]]
deps = ["Mmap"]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
